version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: hello
      DB_PASSWORD: hello
      DB_NAME: db
    depends_on:
      - db

volumes:
  db-data: